Implementation of the buy Shirt feature
dianakrog/automaritionQA pull request #6
Opened 2021-09-15 15:28 UTC by dianakrog

The exception “throws Exception” that is not used in the searchSteps
class is dropped
The annotation AfterAll is changed to After so that it does not affect
the other classes. code is identified
Tefault browser is changed to test with Firefox
The buyShirt feature is created
The buyShirtSteps class is created

2021-09-16 15:14 UTC, aperdomob requested changes
trata de no usar scroll

2021-09-16 15:14 UTC, aperdomob commented on src/test/java/Utils/BrowserManager.java
> +		switch (System.getProperty("exeBrowser","firefox")) {
me explicas porque este cambio y que hace esta linea

2021-09-16 15:14 UTC, aperdomob commented on src/test/java/stepDefinitions/buyShirtSteps.java
> +public class buyShirtSteps {
las clases en Java empiezan con mayusculas

2021-09-16 21:48 UTC, dianakrog commented on src/test/java/Utils/BrowserManager.java
> +		switch (System.getProperty("exeBrowser","firefox")) {
En la clase BrowserManager se ajusta la declaración de la variable exeBrowser de SystemProperty. Esta es la que se recibe desde el CI para identificar con que Browser se ejecuta la prueba. En el switch por defecto se ejecuta con el navegador que esta en el segundo parametro en caso de que no se le pase nada, para el caso Firefox.

2021-09-16 21:49 UTC, dianakrog commented on src/test/java/stepDefinitions/buyShirtSteps.java
> +public class buyShirtSteps {
Se actualiza el nombre de las clases para cumplir el estándar de inicio en Mayúscula. BuyShirtSteps y SearchSteps que tambien tenia este error.

2021-09-20 14:41 UTC, aperdomob approved these changes

2021-09-20 14:41 UTC, merged